apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    db: mongo
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mongo-data"