apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
  namespace: workbuddy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - image: mongodb/mongodb-community-server:latest
          name: mongo
          volumeMounts:
            - name: mongo-vol
              mountPath: /data/db
          ports:
            - name: mongo-port
              containerPort: 27017
          resources: {}
