apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: workbuddy-mongo
  namespace: workbuddy-app
spec:
  ports:
    - port: 9401
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo