apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
  namespace: workbuddy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-vol
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - image: redis
          name: redis
          volumeMounts:
            - name: redis-vol
              mountPath: /data
          ports:
            - name: redis-port
              containerPort: 6379
          resources: {}