apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: workbuddy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
        - image: ajlearnings/workbuddy-api:latest
          name: workbuddy-api
          env:
            - name: MONGO_URI
              value: "mongodb://workbuddy-mongo:9402"
            - name: REDIS_HOST
              value: "workbuddy-redis"
            - name: REDIS_PORT
              value: "9403"
            - name: REDIS_PASSWORD
              value: ""
            - name: SENDER_EMAIL
              value: "<sender-password-here>"
            - name: SENDER_PASSWORD
              value: "<sender-password-here>"
          ports:
            - name: app-port
              containerPort: 9401
          resources: {}