apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: workbuddy-redis
  namespace: workbuddy-app
spec:
  ports:
    - port: 9403
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis