apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper
  name: workbuddy-zookeeper
  namespace: workbuddy-app
spec:
  ports:
    - port: 9404
      protocol: TCP
      targetPort: 2181
  selector:
    app: zookeeper