apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
  namespace: workbuddy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      initContainers:
        - name: check-zookeeper
          image: busybox
          command: [ 'sh', '-c', 'until nc -z workbuddy-zookeeper 9404; do echo waiting for zookeeper; sleep 5; done' ]
      containers:
        - image: confluentinc/cp-kafka:latest
          name: kafka
          ports:
            - name: kafka-port
              containerPort: 9092
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx256m -Xms128m"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "workbuddy-zookeeper:9404"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://workbuddy-kafka:9405"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "134217728"
          resources: {}