apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
  namespace: workbuddy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      initContainers:
        - name: check-mongo
          image: busybox
          command: [ 'sh', '-c', 'until nc -z workbuddy-mongo 9402; do echo waiting for mongo; sleep 5; done' ]
        - name: check-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -z workbuddy-redis 9403; do echo waiting for redis; sleep 5; done' ]
        - name: check-kafka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z workbuddy-kafka 9405; do echo waiting for kafka; sleep 5; done' ]
      containers:
        - image: ajlearnings/workbuddy-api:latest
          name: workbuddy-api
          env:
            - name: MONGO_URI
              value: "mongodb://workbuddy-mongo:9402"
            - name: REDIS_HOST
              value: "workbuddy-redis"
            - name: REDIS_PORT
              value: "9403"
            - name: REDIS_PASSWORD
              value: ""
            - name: SENDER_EMAIL
              value: "<sender-email-here>"
            - name: SENDER_PASSWORD
              value: "<sender-password-here>"
            - name: "KAFKA_URI"
              value: "workbuddy-kafka:9405"
          ports:
            - name: api-port
              containerPort: 9401
          resources: {}