apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: workbuddy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
        - image: ajlearnings/workbuddy-api:v1
          name: workbuddy-api
          env:
            - name: MONGO_HOST
              value: "workbuddy-mongo"
            - name: MONGO_PORT
              value: "9401"
            - name: REDIS_HOST
              value: "workbuddy-redis"
            - name: REDIS_PORT
              value: "9402"
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-cred
                  key: username
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-cred
                  key: password
          ports:
            - name: app-port
              containerPort: 9400
          resources: {}