apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: workbuddy-app
  namespace: workbuddy-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9400
  selector:
    app: app