version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: workbuddy_mongo
    ports:
      - "9402:27017"
    volumes:
      - ./mongo-data:/data/db
  redis:
    image: redis:latest
    container_name: workbuddy_redis
    ports:
      - "9403:6379"
    volumes:
      - ./redis-data:/data
  zookeeper:
    image: zookeeper:latest
    container_name: workbuddy_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "9404:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: workbuddy_kafka_broker
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://workbuddy_kafka_broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 134217728
    ports:
      - "9405:9092"
    depends_on:
      - zookeeper
  workbuddy-api:
    image: ajlearnings/workbuddy-api:latest
    container_name: workbuddy_api
    ports:
      - "9401:9401"
    environment:
      MONGO_URI: mongodb://workbuddy_mongo:27017
      REDIS_HOST: workbuddy_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SENDER_EMAIL: "<sender-email-here>"
      SENDER_PASSWORD: "<sender-password-here>"
      KAFKA_URI: workbuddy_kafka_broker:9092
    depends_on:
      - mongo
      - redis
      - kafka
  workbuddy-ui:
    image: ajlearnings/workbuddy-ui:latest
    container_name: workbuddy_ui
    ports:
      - "9400:80"
    environment:
      API_URL: http://localhost:9401
    depends_on:
      - workbuddy-api
