version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: workbuddy_mongo
    ports:
      - "9402:27017"
    volumes:
      - ./mongo-data:/data/db
  redis:
    image: redis:latest
    container_name: workbuddy_redis
    ports:
      - "9403:6379"
    volumes:
      - ./redis-data:/data
  workbuddy-api:
    image: ajlearnings/workbuddy-api:latest
    container_name: workbuddy_api
    ports:
      - "9401:9401"
    environment:
      MONGO_URI: mongodb://workbuddy_mongo:27017
      REDIS_HOST: workbuddy_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SENDER_EMAIL: "<sender-email-here>"
      SENDER_PASSWORD: "<sender-password-here>"
    depends_on:
      - mongo
      - redis
